name: Update Trending Gist

on:
  schedule:
    - cron: "0 0 * * *"  # 매일 자정 (UTC 기준)
  workflow_dispatch:

jobs:
  update-trending:
    runs-on: ubuntu-latest
    steps:
      - name: Update Gist with trending repos
        uses: matchai/git-trending@master
        with:
          gist_id: e4f3c1aa44212ee45bde29238f299c0a
          token: ${{ secrets.GH_TOKEN }}
          
